/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicWcMatchesRouteImport } from './routes/api/public/wc-matches'

const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWcMatchesRoute = ApiPublicWcMatchesRouteImport.update({
  id: '/api/public/wc-matches',
  path: '/api/public/wc-matches',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/simulator': typeof SimulatorRoute
  '/api/public/wc-matches': typeof ApiPublicWcMatchesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/simulator': typeof SimulatorRoute
  '/api/public/wc-matches': typeof ApiPublicWcMatchesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/simulator': typeof SimulatorRoute
  '/api/public/wc-matches': typeof ApiPublicWcMatchesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/simulator' | '/api/public/wc-matches'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/simulator' | '/api/public/wc-matches'
  id: '__root__' | '/' | '/simulator' | '/api/public/wc-matches'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SimulatorRoute: typeof SimulatorRoute
  ApiPublicWcMatchesRoute: typeof ApiPublicWcMatchesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/wc-matches': {
      id: '/api/public/wc-matches'
      path: '/api/public/wc-matches'
      fullPath: '/api/public/wc-matches'
      preLoaderRoute: typeof ApiPublicWcMatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SimulatorRoute: SimulatorRoute,
  ApiPublicWcMatchesRoute: ApiPublicWcMatchesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
